leftnav:
- identifier: 01a560bb-415e-0942-2521-b5318f923d4e
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 80f5b489-68c5-c228-529a-7ce86c0029f4
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: c1bfdee7-f6c7-b6d4-8905-36920c01ebd1
  name: Assignments
  url: /pages/assignments
  weight: 30
